spring:
  application:
    name: user-center
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/yupi?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
  session:
    timeout: 86400
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)

